// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUJtz3ux-mae2AsBpSj96WHugBTte5i0Y',
    appId: '1:736066830423:web:6ff4b7f63c14eed7ada312',
    messagingSenderId: '736066830423',
    projectId: 'taskify-3c8fa',
    authDomain: 'taskify-3c8fa.firebaseapp.com',
    storageBucket: 'taskify-3c8fa.firebasestorage.app',
    measurementId: 'G-V0S2FM34R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZvf_XKOeWFSZEFGt7YccV0DMuKcaku3s',
    appId: '1:736066830423:android:bd99a2ff4d8d2313ada312',
    messagingSenderId: '736066830423',
    projectId: 'taskify-3c8fa',
    storageBucket: 'taskify-3c8fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLzxX97UCSvc5dnac4CnB4IegZu5UE7AY',
    appId: '1:736066830423:ios:dcc15c3433ca93b4ada312',
    messagingSenderId: '736066830423',
    projectId: 'taskify-3c8fa',
    storageBucket: 'taskify-3c8fa.firebasestorage.app',
    iosBundleId: 'com.example.taskify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLzxX97UCSvc5dnac4CnB4IegZu5UE7AY',
    appId: '1:736066830423:ios:dcc15c3433ca93b4ada312',
    messagingSenderId: '736066830423',
    projectId: 'taskify-3c8fa',
    storageBucket: 'taskify-3c8fa.firebasestorage.app',
    iosBundleId: 'com.example.taskify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUJtz3ux-mae2AsBpSj96WHugBTte5i0Y',
    appId: '1:736066830423:web:c92bc08dccc746e8ada312',
    messagingSenderId: '736066830423',
    projectId: 'taskify-3c8fa',
    authDomain: 'taskify-3c8fa.firebaseapp.com',
    storageBucket: 'taskify-3c8fa.firebasestorage.app',
    measurementId: 'G-P2WL7NTE7J',
  );

}